apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - base/repository.yaml
  # - base/secrets.yaml
  - base/application-argocd.yml
  - base/application-base-tools.yml
  - base/ingress.yaml
  # - overlays/configmap.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.2

patchesStrategicMerge:
  - overlays/service.yml
  - overlays/configmap.yaml
  # - overlays/argocd-secret.yaml

patchesJson6902:
  - path: overlays/deploy-command.yaml
    target:
      group: apps
      kind: Deployment
      name: argocd-server
      version: v1

namespace: argocd
