apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.8.4

patchesStrategicMerge:
  - overlays/service.yml
  - overlays/configmap.yaml
    # - overlays/argocd-secret.yaml

namespace: argocd
patches:
  - path: overlays/deploy-command.yaml
    target:
      group: apps
      kind: Deployment
      name: argocd-server
      version: v1
